/*
 * generated by Xtext 2.18.0
 */
package com.github.gergelyszaz.bgl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension
 * registry.
 */
public class BoardGameLanguageRuntimeModule extends AbstractBoardGameLanguageRuntimeModule {
}
