/*
 * generated by Xtext 2.15.0
 */
package com.github.gergelyszaz.bgl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class BoardGameLanguageStandaloneSetup extends BoardGameLanguageStandaloneSetupGenerated {

	def static void doSetup() {
		new BoardGameLanguageStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
