on:
  push:
    branches:
      - master
name: Deploy Snapshot
jobs:
  deploySnapshot:
    name: Deploy Snapshot
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: deploy snapshot
      uses: gergelyszaz/action-maven-cli@master
      env:
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        OSSRH_USERNAME: gergelyszaz
      with:
        args: clean deploy
